### ISSUE TITLE
Release for thymeleaf 2 ?

### ISSUE THREAD

**Issue by sergiofbsilva** [jpenren/thymeleaf-spring-data-dialect#1]
Can you deploy the thymeleaf 2 branch in maven central ? :+1: 

Thanks!

**Comment by jpenren** [comment]
I have to fix some bugs on this branch, after that, i'll upload the thymeleaf 2 version to Maven.
Regards

**Comment by jpenren** [comment]
Release 2.0.0, compatible with Thymeleaf 2, uploaded to Maven Central:
<dependency>
	<groupId>io.github.jpenren</groupId>
	<artifactId>thymeleaf-spring-data-dialect</artifactId>
	<version>2.0.0</version>
</dependency>
