### ISSUE TITLE
How to custom style?

### ISSUE THREAD

**Issue by hukacode** [jpenren/thymeleaf-spring-data-dialect#10]
Hi,

Can you help me how to custom style PageSizeSelector?
Or can I build "Page size selector", "Pagination" for myself?
>>
I saw your answer at: https://github.com/jpenren/thymeleaf-spring-data-dialect/issues/9#issuecomment-249156264

But I have a new question. When I override **PageSizeSelector.properties**, will I have to override other files? (_de, _en, _fr,..)

**Comment by jpenren** [comment]
PageSizeSelector don't need language specific properties, only one file exists for this component

**Comment by hukacode** [comment]
Hi @jpenren ,

Thank you for your reply. I'm so sorry for my mistake. It's should be **FullPaginationDecorator**.

By the way, is it have alternative for modify style? What if I use Material Design Lite, all I need to do is override FullPaginationDecorator_*.properties?
I used version 2.1.1 for Thymeleaf 2.

Regards,
Huka

**Comment by jpenren** [comment]
yes, to modify the structure of the elements (not just css) do you need to override all related properties files or at least languages that do you want to support on your app
