### ISSUE TITLE
What would be the best way to add sort icons in the table header?

### ISSUE THREAD

**Issue by wimdeblauwe** [jpenren/thymeleaf-spring-data-dialect#16]
I would like to have sort icons in the table header so the user visually sees that there is sorting being applied. What would be the preferred way to do this?

**Comment by jpenren** [comment]
Here is a simple way with FontAwesome icons:
```
table.table thead .sorted:after{
	display: inline-block;
	font-family: 'FontAwesome';
	opacity: 0.8;
	margin-left: 1em;
}
table.table thead .sorted.sorted-desc:after{
	content: "\f15e";
}
table.table thead .sorted.sorted-asc:after{
	content: "\f15d";
}
```

**Comment by wimdeblauwe** [comment]
Thanks, we did it in the end with unicode characters like this:

```
.sorted-desc::after, .sorted-asc::after {
    float: right;
}

.sorted-desc::after{
    content:"\25BC";
}

.sorted-asc::after{
    content: "\25B2";
}
```

You want me to create a PR to update the docs to include the both examples?

**Comment by jpenren** [comment]
of course, all contributions are welcome!

**Comment by wimdeblauwe** [comment]
I added PR https://github.com/jpenren/thymeleaf-spring-data-dialect/pull/18 with the changes.
