### ISSUE TITLE
About i18n...

### ISSUE THREAD

**Issue by xuyuanxiang** [jpenren/thymeleaf-spring-data-dialect#25]
I need some help..

I follewd the source code and appended a file : `/resources/thymeleaf-spring-data-dialect/PaginationSummary_zh_CN.properties` to my project:

`pagination.summary=当前 {0} 至 {1} 条，共 {2} 条。`

but I got this:

![](http://cdn.xuyuanxiang.me/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-05-15%2015.45.06.png)

**Comment by sis-yoshiday** [comment]
@xuyuanxiang 

You need to encode property file by `native2ascii`

```bash
native2ascii [path_to_your_PaginationSummary_zh_CN.properties]
```

and paste encoded result to your property file.

**Comment by jpenren** [comment]
Support for chinese on v3.4.0+
