### ISSUE TITLE
unidirectional sorts

### ISSUE THREAD

**Issue by mnoky** [jpenren/thymeleaf-spring-data-dialect#35]
Hi, thanks so much for this fantastic project! Been using it extensively in my latest project.

I recently had the use case where I needed to allow a unidirectional sort for certain columns (i.e. either ascending only or descending only). I came up with a solution that introduces two new attribute processors: pagination-sort-asc and pagination-sort-desc. Wondering what you thought about adding this functionality?

**Comment by wimdeblauwe** [comment]
Shouldn't this issue be closed given #37 has been merged ?
