### ISSUE TITLE
migrate to spring-boot 3.0.0 and spring-webmvc-6.0.0 

### ISSUE THREAD

**Issue by thomaswoehlke** [jpenren/thymeleaf-spring-data-dialect#44]
- spring-webmvc-6.0.0 
- spring-security-test-6.0.0
- spring-security-web-6.0.0

Test-Application: https://github.com/BloodMoneyApp/bloodmoney/tree/branch_BOOT3

**Comment by thomaswoehlke** [comment]
meanwhile spring-boot 3.0.0 and spring-frameworks-6.0.0 are released.

**Comment by kacetal** [comment]
@jpenren PR is merged, could you create new release for this issue please?

**Comment by jpenren** [comment]
Release 3.6.0 published
