### ISSUE TITLE
Thymeleaf 3 support/issues?

### ISSUE THREAD

**Issue by tedwards-rogue** [jpenren/thymeleaf-spring-data-dialect#6]
Based on the documentation, it looks like the support for Thymeleaf 3 will be in version 3 of the application. 
What issues are you aware of that would keep someone from using this for Thymeleaf 3? 

Do you have an expected due date of when you might be able to release a compatible version with Thymeleaf 3?

**Comment by jpenren** [comment]
Version 3.0.0 released and available from maven central

```xml
<dependency>
	<groupId>io.github.jpenren</groupId>
	<artifactId>thymeleaf-spring-data-dialect</artifactId>
	<version>3.0.0</version>
</dependency>
```
