### ISSUE TITLE
Define size of num of entries in the table

### ISSUE THREAD

**Issue by kanisso** [jpenren/thymeleaf-spring-data-dialect#9]
Hello,

I'm trying override num of entries in the `<span sd:page-size-selector="javascript"></span>`.
Component working perfectly, but I want that the default number is 10, not 20.

How I can do it?

Regards!

**Comment by jpenren** [comment]
This requires a little modification, i will move the selector values to the .properties file, by this way you can customize the showing values

**Comment by kanisso** [comment]
When you expect have this in new release?

**Comment by jpenren** [comment]
Released!
```xml
<dependency>
    <groupId>io.github.jpenren</groupId>
    <artifactId>thymeleaf-spring-data-dialect</artifactId>
    <version>3.2.0</version>
</dependency>
```

Now, create this file on your project: src/main/resources/thymeleaf-spring-data-dialect/PageSizeSelector.properties to override the selector values, you can copy the content from https://github.com/jpenren/thymeleaf-spring-data-dialect/blob/master/src/main/resources/thymeleaf-spring-data-dialect/PageSizeSelector.properties

**Comment by kanisso** [comment]
Hello,
Thanks for reply.

I already copy your file, and I can customize the list, but i can't define the default selected value. 
When the list have 20, 20 is selected automatically, else it's selected the first one.

**Comment by jpenren** [comment]
Page size selector gets the the selected value from Page object on the request, if you want to modify the default value do any of the following alternatives:
- Add @PageableDefault(size=NN)
```java
public String list(ModelMap model, @PageableDefault(size=10) Pageable pageable){
	model.addAttribute("page", userService.findAll(pageable));
		
	return "configuration/users/list";
}
```
- Configure the Spring Data page size default value: http://stackoverflow.com/questions/27032433/set-default-page-size-for-jpa-pageable-object

**Comment by hukacode** [comment]
Hi @kanisso,

Can you show me your config? I used:
```
    <thymeleaf.version>3.0.2.RELEASE</thymeleaf.version>
    <thymeleaf-extras-springsecurity4.version>3.0.0.RELEASE</thymeleaf-extras-springsecurity4.version>
    <thymeleaf-layout-dialect.version>2.0.3</thymeleaf-layout-dialect.version>
    <thymeleaf-extras-data-attribute.version>2.0.1</thymeleaf-extras-data-attribute.version>
    <thymeleaf-spring-data-dialect.version>3.2.0</thymeleaf-spring-data-dialect.version>
    <thymeleaf-extras-java8time.version>3.0.0.RELEASE</thymeleaf-extras-java8time.version>
```
and

> create this file on your project: src/main/resources/thymeleaf-spring-data-dialect/PageSizeSelector.properties to override the selector values

but still didn't show my customize.

**Comment by kanisso** [comment]
<thymeleaf.version>3.0.1.RELEASE</thymeleaf.version>
        <thymeleaf.spring.data.dialect.version>3.2.0</thymeleaf.spring.data.dialect.version>

        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf</artifactId>
            <version>${thymeleaf.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf-spring4</artifactId>
            <version>${thymeleaf.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.github.jpenren</groupId>
            <artifactId>thymeleaf-spring-data-dialect</artifactId>
            <version>${thymeleaf.spring.data.dialect.version}</version>
        </dependency>

and in file 
page.size.selector.values=10,25,50,100

**Comment by hukacode** [comment]
Look like my config. (cwl)
![hkblog1.png](http://2.pik.vn/2016f3d9cf5a-eec0-4383-8bb4-623268d9ef43.png)

**Comment by hukacode** [comment]
@kanisso 
Thank you for your response. I can customize PageSizeSelector.properties now. But  PagerDecorator.properties is not, may be it's not supported.

Regards,
Huka.
